<a href="https://colab.research.google.com/github/rajneeshanand/pytorch_RJ/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**LISTS**

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**Numpy arrays**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.45345185, 0.06870039, 0.25848615, 0.23839206],
       [0.78217736, 0.46569058, 0.15868443, 0.54697126],
       [0.42763533, 0.06378278, 0.31370882, 0.18555018]])

In [6]:
np1.dtype

dtype('float64')

**Tensors**

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.1892, -1.7266,  1.3211, -0.0332],
        [ 0.7220, -0.2824, -0.7158, -0.6287],
        [-0.4836, -0.2676,  0.1667,  0.2348]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## create tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4535, 0.0687, 0.2585, 0.2384],
        [0.7822, 0.4657, 0.1587, 0.5470],
        [0.4276, 0.0638, 0.3137, 0.1856]], dtype=torch.float64)